/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/batches` | `/batches`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/leads` | `/leads`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/watcher` | `/watcher`; params?: Router.UnknownInputParams; } | { pathname: `${'/(lead)'}/expenses` | `/expenses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(lead)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(lead)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/batches` | `/batches`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/leads` | `/leads`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/watcher` | `/watcher`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(lead)'}/expenses` | `/expenses`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(lead)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(lead)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/batches${`?${string}` | `#${string}` | ''}` | `/batches${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/leads${`?${string}` | `#${string}` | ''}` | `/leads${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/watcher${`?${string}` | `#${string}` | ''}` | `/watcher${`?${string}` | `#${string}` | ''}` | `${'/(lead)'}/expenses${`?${string}` | `#${string}` | ''}` | `/expenses${`?${string}` | `#${string}` | ''}` | `${'/(lead)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(lead)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/batches` | `/batches`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/leads` | `/leads`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/watcher` | `/watcher`; params?: Router.UnknownInputParams; } | { pathname: `${'/(lead)'}/expenses` | `/expenses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(lead)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(lead)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
    }
  }
}
